---

scheduler-config:
    class: 'apscheduler.jobstores.shelve_store:ShelveJobStore'
    path: '/tmp/dbfile'

days: 'mon-fri'
hour: 23
minute: 59

directory: 'scitech'

url: 'http://localhost:1338/'

file-format: '.xml'

...